/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-04-24 01:13:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.shop;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import java.util.List;
import shop.dto.Product;
import shop.dao.ProductRepository;

public final class update_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("shop.dto.Product");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("shop.dao.ProductRepository");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>상품수정</title>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/layout/meta.jsp", out, false);
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/layout/link.jsp", out, false);
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	");

	String root = request.getContextPath();

	String productId = request.getParameter("id");
	ProductRepository productDAO = new ProductRepository();
	Product product = productDAO.getProductById(productId);
	
      out.write("\r\n");
      out.write("	<!-- 헤더 -->\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/layout/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"px-4 py-5 my-5 text-center\">\r\n");
      out.write("		<h1 class=\"display-5 fw-bold text-body-emphasis\">상품 수정</h1>\r\n");
      out.write("		<div class=\"col-lg-6 mx-auto\">\r\n");
      out.write("			<p class=\"lead mb-4\">Shop 쇼핑몰 입니다.</p>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- 상품 수정 입력 화면 -->\r\n");
      out.write("	<div class=\"container shop\">\r\n");
      out.write("		<form name=\"product\" action=\"./update_pro.jsp\" onsubmit=\"return checkProduct()\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"input-group mb-3 row\">\r\n");
      out.write("				<img src=\"");
      out.print(root);
      out.write("/shop/img?id=");
      out.print(product.getProductId());
      out.write("\"\r\n");
      out.write("					class=\"w-100 p-2\">\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"input-group mb-3 row\">\r\n");
      out.write("				<label class=\"input-group-text col-md-2\" id=\"\">상품 이미지</label> <input\r\n");
      out.write("					type=\"file\" class=\"form-control col-md-10\" name=\"file\">\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"input-group mb-3 row\">\r\n");
      out.write("				<label class=\"input-group-text col-md-2\" id=\"\">상품 코드</label> <input\r\n");
      out.write("					type=\"text\" class=\"form-control col-md-10\" name=\"productId\"\r\n");
      out.write("					value=\"");
      out.print(product.getProductId());
      out.write("\" readonly=\"\">\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"input-group mb-3 row\">\r\n");
      out.write("				<label class=\"input-group-text col-md-2\" id=\"\">상품명</label> <input\r\n");
      out.write("					type=\"text\" class=\"form-control col-md-10\" name=\"name\"\r\n");
      out.write("					value=\"");
      out.print(product.getName());
      out.write("\">\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"input-group mb-3 row\">\r\n");
      out.write("				<label class=\"input-group-text col-md-2\" id=\"\">가격</label> <input\r\n");
      out.write("					type=\"number\" class=\"form-control col-md-10\" name=\"unitPrice\"\r\n");
      out.write("					value=\"");
      out.print(product.getUnitPrice());
      out.write("\">\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"input-group mb-3 row\">\r\n");
      out.write("				<label class=\"input-group-text col-md-2\" id=\"\">상세 정보</label>\r\n");
      out.write("				<textarea class=\"form-control col-md-10\" name=\"description\" rows=\"5\">");
      out.print(product.getDescription());
      out.write("</textarea>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"input-group mb-3 row\">\r\n");
      out.write("				<label class=\"input-group-text col-md-2\" id=\"\">제조사</label> <input\r\n");
      out.write("					type=\"text\" class=\"form-control col-md-10\" name=\"manufacturer\"\r\n");
      out.write("					value=\"");
      out.print(product.getManufacturer());
      out.write("\">\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"input-group mb-3 row\">\r\n");
      out.write("				<label class=\"input-group-text col-md-2\" id=\"\">분류</label> <input\r\n");
      out.write("					type=\"text\" class=\"form-control col-md-10\" name=\"category\"\r\n");
      out.write("					value=\"");
      out.print(product.getCategory());
      out.write("\">\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"input-group mb-3 row\">\r\n");
      out.write("				<label class=\"input-group-text col-md-2\" id=\"\">재고 수</label> <input\r\n");
      out.write("					type=\"number\" class=\"form-control col-md-10\" name=\"unitsInStock\"\r\n");
      out.write("					value=\"");
      out.print(product.getUnitsInStock());
      out.write("\">\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"input-group mb-3 row\">\r\n");
      out.write("				<label class=\"input-group-text col-md-2\" id=\"\">상태</label>\r\n");
      out.write("				<div class=\"col-md-10 d-flex align-items-center\">\r\n");
      out.write("					<div class=\"radio-box d-flex\">\r\n");
      out.write("						<div class=\"radio-item mx-5\">\r\n");
      out.write("							<input type=\"radio\" class=\"form-check-input\" name=\"condition\" value=\"NEW\" id=\"condition-new\"> \r\n");
      out.write("							<label for=\"condition-new\">신규 제품</label>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"radio-item mx-5\">\r\n");
      out.write("							<input type=\"radio\" class=\"form-check-input\" name=\"condition\" value=\"OLD\" id=\"condition-old\"> \r\n");
      out.write("							<label for=\"condition-old\">중고 제품</label>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"radio-item mx-5\">\r\n");
      out.write("							<input type=\"radio\" class=\"form-check-input\" name=\"condition\" value=\"RE\" id=\"condition-re\"> \r\n");
      out.write("							<label for=\"condition-re\">재생 제품</label>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"d-flex justify-content-between mt-5 mb-5\">\r\n");
      out.write("				<a href=\"./products.jsp\" class=\"btn btn-lg btn-secondary\">목록</a>\r\n");
      out.write("				<input type=\"submit\" class=\"btn btn-lg btn-success\" value=\"수정\">\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/layout/footer.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/layout/script.jsp", out, false);
      out.write("\r\n");
      out.write("	<script src=\"/static/js/validation.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("    // JSP 코드로부터 가져온 상태 정보\r\n");
      out.write("    let condition = \"");
      out.print( product.getCondition() );
      out.write("\"; // 문자열로 가져옵니다.\r\n");
      out.write("\r\n");
      out.write("    // 가져온 상태 정보를 사용하여 해당 라디오 버튼을 선택\r\n");
      out.write("    let radioCondition = document.getElementById(\"condition-\" + condition.toLowerCase()); // 소문자로 변환하여 id를 찾습니다.\r\n");
      out.write("    if (radioCondition) { // 해당 상태에 해당하는 라디오 버튼이 존재하는지 확인\r\n");
      out.write("        radioCondition.checked = true;\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
